[colors.primary]
background = '#11121d'
foreground = '#f0f0f0'
dim_foreground    = '#dbdbdb'
bright_foreground = '#d9d9d9'

[colors.cursor]
text   = '#2c2c2c'
cursor = '#d9d9d9'

[colors.normal]
black   = '#2a2c3f'
red     = '#e2506b'
green   = '#84d350'
yellow  = '#e6c364'
blue    = '#6d8fff'
magenta = '#a775be'
cyan    = '#45bbce'
white   = '#9fa2df'

[colors.bright]
black   = '#263266'
red     = '#ff3459'
green   = '#3fff0f'
yellow  = '#ffde23'
blue    = '#256aff'
magenta = '#b340ff'
cyan    = '#14dcff'
white   = '#acb0d0'

[colors.dim]
black   = '#232323'
red     = '#8b3f3b'
green   = '#588041'
yellow  = '#b39032'
blue    = '#556b79'
magenta = '#6e4962'
cyan    = '#61b1ad'
white   = '#9b9b9b'
